# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileReceiver',
        ),
        migrations.AlterModelOptions(
            name='userprofilereporter',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868'},
        ),
    ]
